### ISSUE TITLE
Approve friend request, missing entry

### ISSUE THREAD

**Issue by MBlondin** [ColdTrick/friend_request#15]
When the entity (entities table) for the friend approval, the owner_guid is set to 0.  Should it not be set to the user GUID that approves the friend request?  We are on elgg 1.12.9 and Friend_request v4.0

**Comment by jdalsem** [comment]
Which entity do you mean? Or do you mean the relationship?

**Comment by jdalsem** [comment]
Please let me know if you have more details on this issue. I can reopen it then...
