### ISSUE TITLE
notification of a friend request in topbar, but no requests visible

### ISSUE THREAD

**Issue by propertunist** [ColdTrick/friend_request#17]
i currently have a count of 1 new friend requests as admin on my live site, but when i view the friend request page i don't see any listed.
any idea how to debug this quickly?

**Comment by jeabakker** [comment]
could it maybe be a disabled user? So a not yet verified user?

**Comment by propertunist** [comment]
i don't think so - but there is apparently a bug with the 'delete account' process, so that is not impossible. i just got informed that someone else is seeing the same problem in their account too. i have asked for the name of who sent the friend request as he can see it in the notifications popup.

**Comment by propertunist** [comment]
ah so, it was not a disabled user who sent the friend request to the other user

**Comment by propertunist** [comment]
i found the cause. matt's 'extendafriend' plugin needs to be upgraded.
