### ISSUE TITLE
Spacing in header at symbol and number spacing is off

### ISSUE THREAD

**Issue by Badbo** [ColdTrick/friend_request#18]
TopBarMenu.php
'text' => elgg_view_icon('user') . elgg_format_element('span', ['class' => 'friend-request-new'], $count),
replace with
"text" => elgg_view_icon("user") . "<span class=\"messages-new\">" . $count . "</span>",

**Comment by jeabakker** [comment]
that would only work if you have the `messages` plugin enabled, otherwise there would be no styling at all.

It's off by 2px you can change it in your theme by adding a css rule:
```css
.friend-request-new {
	left: 26px;
}
```

**Comment by Badbo** [comment]
Ok super thanks, i will do that if i disable the message plugin other wise it is pretty ugly.
