### ISSUE TITLE
Only one river entry needed when a 2 way friendship is established

### ISSUE THREAD

**Issue by daniyaree** [ColdTrick/friend_request#20]
It shows two separate and simultaneous River entries when a 2 way friendship is established.
Only one should be sufficient.
At present, it shows 
"abc is now a friend with xyz"
"xyz is now a friend with abc"
Only one is needed and much better, for example
"xyz and abc are now freinds"

**Comment by jdalsem** [comment]
I get this would make sense, but it currently is required because of Elgg logic where a river activity is done by a single user
