### ISSUE TITLE
'create', 'friend' event handlers are removed

### ISSUE THREAD

**Issue by beck24** [ColdTrick/friend_request#4]
In the add/approve friend actions, the event handlers are forcefully removed before reciprocally adding the friends.  I need to perform some tasks at that time and can't find a way of doing so without forking this and specifically adding in my handler.
For a future release, would it be possible to trigger a custom event here for other plugin authors that are building around friendships with friend_request specifically in mind?

Please and thanks!

**Comment by jdalsem** [comment]
@jeabakker why did you reopen this ticket?

**Comment by beck24** [comment]
I haven't tested this specific use case since this came up, but I don't see any reason why using default handlers would be an issue.  I'd consider this closed.
